FactomProject/factomd

- common/messages/missingMsg.go
- common/messages/missingMsgResponse.go
- common/messages/serverFault.go
> Add sanity (nil-check) validation to multiple messagetypes

- common/messages/dbstate.go
- common/messages/dbstate_test.go
- common/messages/directoryBlockSignature.go
- engine/printSummary.go
- engine/simControl.go
- state/dbStateManager.go
- state/processList.go
- state/processListManager.go
- state/saveAndRestore.go
- state/state.go
- state/stateConsensus.go
- state/stateDisplay.go
- state/state_test.go
- testHelper/testHelper_test.go
- wsapi/wsapiV2.go
> Backed out changes to save at minute 1.  Added debugging features

- scripts/entryloadm2.sh
- state/factoidstate.go
- state/state.go
- state/stateConsensus.go
JIRA-340
Big stability fix.  Fixes entry chain and entry transactions.
> Fixed the search for and request for missing entries and entryblocks

- engine/simControl.go
Simulation only.  No runtime impact.
> Sof 258 fix nul pointer, direct output to stderr

- state/state.go
> Change default period for fault timeouts

- common/messages/dbstate.go
- common/messages/directoryBlockSignature.go
- engine/simControl.go
- state/dbStateManager.go
- state/fault.go
- state/processList.go
- state/state.go
- state/stateConsensus.go
More work to fix issues with changing the dbstate handling.
Added debugging messages and logging in many places.
Did some cleanup related to logging.
Removed faulting messages that are out of date from holding.
> Checkpoint of better working dbstate handling

- common/messages/dbstate.go
- common/messages/directoryBlockSignature.go
- state/dbStateManager.go
- state/processList.go
- state/stateConsensus.go
Better catch up after divergence or faults.
> Sof 399 More tweaks

- util/config.go
fixed print statement from config file reader.
> removed debug statement

- engine/simAuthorities.go
- wsapi/wsapi.go
- wsapi/wsapiV2.go
Reverts FactomProject/factomd#88
> Revert "Sof 492"

- all.sh
- common/messages/MessageBase.go
- common/messages/revealEntry.go
- glide.lock
- glide.yaml
- scripts/entryloadm2.sh
- state/stateConsensus.go
Reverts FactomProject/factomd#95
> Revert "Updates to scripts (low risk, all.sh entryloadm2.sh) lowered resend r…"

- all.sh
- glide.lock
Made all.sh script pull appropriate branches from git, then glide them.
Updated the lock file for factomd
> Fixed lock file, updated all.sh to use glide

- state/processListManager.go
> Check index before using

- p2p/parcel.go
- p2p/protocol.go
Adjust MaxPayloadSize and NetworkDeadline
> Increase NetworkDeadline, increase MaxPayloadSize

- p2p/connection.go
- p2p/controller.go
- p2p/parcel.go
Playing safe vis-a-vis GC (less detritus lying around)
> Clobber the parcel's parts after reassembling the Parcel

- p2p/parts_assembler.go
Invalid parcel parts are now rejected
> SOF-533: Validate parcel part before assembling

- p2p/controller.go
- p2p/protocol.go
* Increase network timeout 10s -> 30s
* Increase the size of the network -> app channel 10 000 -> 100 000 -
this allows handling more packets of smaller size
> SOF-514: adjust network settings

- p2p/controller.go
- p2p/protocol.go
Instead of changing only the FromNetwork channel
> Adjust StandardChannelSize to 100000

- common/messages/bounce.go
- common/messages/dbstate.go
- common/primitives/util.go
- common/primitives/util_test.go
- netTest/NetworkTest.go
- state/entrySyncing.go
This also involves debugging the DBState loading, which is hard to read.
That is also fixed here.
Also some go formatting.
> Address the Entry and DBState loading getting out of sync

- common/adminBlock/EntryServerFault.go
It looks like EntryServerFault wasn't marshalling its type.
> Fixed a small issue with EntryServerFault

- engine/simControl.go
Also some excess code line cleanup in the sim control.
> Some logic cleanup to prevent panics in simcontrol

- p2p/connection.go
Double the time set for the deadline to write.
> Sof 70 double write deadline

- common/factoid/fblock_test.go
- common/factoid/transaction_test.go
- common/interfaces/transaction.go
- common/primitives/util.go
- common/primitives/util_test.go
merge in the last of piotr's unit tests.
> Piotr test2

- common/factoid/fblock_test.go
- common/factoid/transaction_test.go
- common/interfaces/transaction.go
- common/primitives/util.go
- common/primitives/util_test.go
> Peter testing

- common/directoryBlock/directoryBlock.go
- common/directoryBlock/directoryBlockEntry_test.go
- common/directoryBlock/directoryBlockHeader_test.go
- common/directoryBlock/directoryBlock_test.go
- database/leveldb/leveldb.go
- p2p/connection.go
Here is some additional coverage and bugfixes for the factomd repo.
> coverage updates, etc

- engine/NetStart.go
- engine/profiler.go
- glide.lock
- glide.yaml
- state/entrySyncing.go
- state/instrumentation.go
Adding in prometheus instrumentation
> Sof 70 tweak2 prometheus

- controlPanel/dataDumpFormatting/servers.go
- engine/simControl.go
- state/authority.go
- state/identity.go
- state/identityUtils.go
- wsapi/debugapi.go
- wsapi/wsapiV2.go
Added api call to get authority set. 
Made structs have json tags
> Exposed a debug API for authorities

- state/dbStateManager_test.go
- state/stateConsensus.go
- testHelper/testHelper.go
This test fails. It tests saving to a database
> Added a test to check DBState saving

- state/dbStateManager_test.go
- state/processList.go
- state/stateConsensus.go
- testHelper/fBlock.go
- testHelper/testHelper.go
Has additonal steps in the DBStateManager_test
No longer delete DBlock when fail signature check. The DBlock should never be written
> Fd 33 dbtest

- glide.lock
This updates the levelDB version with a few of the upstream updates.
> update leveldb to latest version

- p2p/protocol.go
> back out network optimizations

- common/messages/dbstate.go
- common/messages/dbstate_test.go
- common/messages/directoryBlockSignature.go
- common/messages/revealEntry.go
- controlPanel/controlPanel.go
- controlPanel/controlPanel_test.go
- controlPanel/dataDump.go
- engine/SimPeer_test.go
- engine/simControl.go
- state/dbStateManager.go
- state/dbStateManager_test.go
- state/fault.go
- state/processList.go
- state/saveAndRestore.go
- state/state.go
- state/stateConsensus.go
- state/stateDisplay_test.go
- state/state_test.go
FD-105 has FD-99, FD-100, and FD-101 merged in.
Removed the lists for commits... made the code too complex
Fixed nil pointer issues.
> Fd 105:  Fixes the DBState sync issue, message sync issue, and more

- state/dbStateManager.go
- state/processListManager.go
- state/stateConsensus.go
The problem is that we apply the dbstate while syncing, leaving the variables we are using to sync in a mess.  This fix says, if you are the leader, don't do that.  Wait to apply the dbstate until syncing is complete.
> Fd 158: Network stalls

- Dockerfile
Pull deps before copying sources (speed up builds)
> Move from alpine to ubuntu (ease copying)

- engine/NetStart.go
- engine/factomParams.go
- engine/profiler.go
This allows for remote diagnosis of performance issues
> Ability to expose profiling

- database/database.go
- database/securedb/encryptedMarshaler.go
- database/securedb/encryptedMarshaler_test.go
- database/securedb/encryption.go
- database/securedb/encryption_test.go
- database/securedb/metadata.go
- database/securedb/metadata_test.go
- database/securedb/securedb.go
- database/securedb/securedb_test.go
- database/test_databases_test.go
- glide.lock
Also made unit test test all interface.IDatabases
> Added a secure database with encryption around puts/gets

- .circleci/config.yml
- .travis.yml
- Docker.md
- Dockerfile.alpine
- README.md
Also add support for alpine containers
> Add CircleCI support

- common/messages/commitChain.go
- common/messages/commitChain_test.go
Should also remove signature from CommitEntryMsg
> Remove signature field from CommitChainMsg.  Field is unused in practice

- engine/factomParams.go
- engine/factomd_test.go
> verbump II

- LICENSE
- README.md
Also thanks to https://github.com/ianwelsh for a typo fix.
> Fd 307 license update

- engine/NetStart.go
- state/entrySyncing.go
This reverts commit c9d771be191fe85eb9803e6a1274a3bbf25e3f88.
> FD-326 Revert "Saved the second pass data"

- .circleci/config.yml
- .dockerignore
Also, Ignore vendor/ when building
> Build on tag pushes

- README.md
Change the spacing for the markdown readme.md so the header is properly formatted.
> readme markdown edit

- support/dev/README.md
- support/dev/docker-compose.yml
- support/dev/elasticsearch/Dockerfile
- support/dev/elasticsearch/config/elasticsearch.yml
- support/dev/kibana/Dockerfile
- support/dev/kibana/config/kibana.yml
- support/dev/logstash/Dockerfile
- support/dev/logstash/config/logstash.yml
- support/dev/logstash/pipeline/logstash.conf
- support/dev/prometheus/Dockerfile
- support/dev/prometheus/config/prometheus.yml
> Docker-compose based dev environment

- common/messages/missingMsg.go
Fixes the duplication of missing message requests.
> Fix FD-377 missing messages are repeated because the height is repeated

- wsapi/wsapiV2.go
Clean up a few debug prints in FD-567
> removed print lines

- state/processList.go
FD-602_CalculateSystemStatusAlways_mergeable
> FD-602_CalculateSystemStatusAlways_mergeable

- common/messages/electionMsgs/electionMsgTesting/controller.go
- state/processListManager_test.go
- state/stateFER.go
- test.sh
- testHelper/testHelper.go
- wsapi/wsapiV2_test.go
> Fd 706 myork

- .circleci/config.yml
- LICENSE
- LongTests/ChainTransaction_test.go
- engine/factomd_test.go
- engine/simAuthorities.go
- engine/simWallet.go
- glide.lock
- glide.yaml
- state/validation.go
- test.sh
- testHelper/simulation.go
- testHelper/testHelper.go
- testHelper/testHelper_test.go
NOTE: this still has the long-running chained transaction tests - will tune it separately
> Fd 721 testing refactor and sim wallet rc

- state/state.go
- state/stateConsensus.go
- state/validation.go
We stall after an hour... and some minor performance issues.
> Fixes to the dev branch

- state/crossBootReplay.go
pull request for issue https://github.com/FactomProject/factomd/issues/643
Changed to calculate the time of completion once when initialized, then checking if that time has passed
> crossreplayfilter garbage collection termination fix

- CLA.txt
- state/grants.go
These are all grants that have been approved by the standing parties during grant round 2019-1.
Addresses and amounts have been verified with recipients and reverification based on the code change has been requested to all recipients.
Please double check activation height of 180993. Activation should happen at 23-02-2019 00:00 UTC (not before)
> Add 2019-1 grants approved by standing parties to Fd 820 release candidate butter

- common/interfaces/state.go
- state/state.go
- wsapi/wsapiStructs.go
- wsapi/wsapiV2.go
#664 
This relies on DBFinished in state rather than checking if IgnoreDone.
> Add lastblockfromdbstate to diagnostics API

- state/dbStateCatchup.go
- state/state.go
- util/config.go
changed DBStateCatchup to use LLeaderHeight instead of HighestSavedBlk and change config to have the DBState missing request timeout default to 1/10th of the block time
> Fd 928 db state missing err

- common/interfaces/state.go
- state/state.go
- wsapi/wsapi.go
Anton requested to know if ignore was done.
> Added IgnoreDone prop

- engine/SimPeer.go
- engine/simControl.go
- state/stateConsensus.go
> Fd 1012 resend msgs left in holding

- simTest/HoldingRebound_test.go
- testHelper/simWallet.go
- testHelper/simulation.go
Correct unit test sporadic failures
> Fd 1058 simtest shutdown

- README.md
- common/factoid/fblock.go
- common/messages/electionMsgs/fedVoteMsg.go
- controlPanel/controlPanel.go
- elections/elections.go
- electionsCore/interpreter/interpreter/interpreter.go
- engine/NetStart.go
- engine/NetworkProcessorNet.go
- engine/factomParams.go
- p2p/protocol.go
- state/MMR.go
- state/plugins.go
- state/stateConsensus.go
- state/validation.go
there's one bugfix in there that might change behavior, the other commits should not change behavior in any way
> Fd 831 legibility improvements batch 1

- Utilities/BalanceFinder/main.go
- Utilities/CorrectChainHeads/main.go
- Utilities/tools/fetcher.go
- glide.lock
Also refactored CorrectChainHeads to use same tool code
as BalanceFinder. Refactored to match new function definitions in
/factom
> FD-621 : Correct BalanceFinder utility to compile

- common/identity/authority.go
- common/identity/authority_test.go
Simple change to include missing fields in json marshal
> FD-562 : Correct authority marshalling

- controlPanel/controlPanel.go
- engine/profiler.go
Continuation of https://github.com/FactomProject/factomd/pull/767
(Rebased branch onto 821, had to make a new branch to avoid merge)
> Fd 925 use different web service muxes rebase

- state/crossBootReplay.go
Continuation of https://github.com/FactomProject/factomd/pull/644
Rebased onto parchment
> FD-819 : crossreplayfilter garbage collection termination fix

- engine/MsgLogging.go
Continuation of https://github.com/FactomProject/factomd/pull/746
By @WhoSoup
> Fd 1069 runtimelog honoring

- engine/NetStart.go
- engine/simAuthorities.go
- simTest/EntriesBeforeChain_test.go
- testHelper/testHelper_test.go
- AddFnode0 moved
- Fixed unit test with chain+entry testing
- Added some testhelper unit test
> FD-833 : Brought in changes manually

- common/interfaces/state.go
- controlPanel/controlPanel.go
- state/state.go
- state/stateDisplay.go
extend control panel to query ignore status
> Fd 869 add ignore to control panel batch api

- Utilities/DatabaseGenerator/blockgen/generator.go
- Utilities/DatabaseGenerator/main.go
- Utilities/DatabaseGenerator/smallblocks.yaml
Correct database generator tool
> FD-1091 : Update to database generation utility

- common/messages/ack.go
- common/messages/revealEntry.go
- engine/factomd_test.go
- engine/printSummary.go
- log/log_test.go
- p2p/controller.go
- p2p/parts_assembler.go
- p2p/peer.go
- simTest/EntriesBeforeChain_test.go
- simTest/EntryBatch_test.go
- state/HoldingList.go
- state/factoidstate.go
- state/stateConsensus.go
tweak to pull held messages out of new dependent holding when 
follower executing 
May help w/ MMR improvement testing
> Fd 1105 follower exec ack depholding

- simTest/EntriesBeforeChain_test.go
- simTest/EntryBatch_test.go
- simTest/HoldingRebound_test.go
- simTest/PermFCTBalancesAfterMin9Election_test.go
- testHelper/simulation.go
> import test from old work

- CLA
- activations/activationHeight.go
- anchor/anchorRecord.go
- anchor/anchorRecord_test.go
- common/primitives/json.go
- common/primitives/key.go
- common/primitives/log.go
- common/primitives/log_test.go
- testHelper/eBlock.go
1) Adding Comments
2) Adding tests
3) removing code duplication via refactor
4) make receivers consistent naming
etc
> FD-1114 Xuan factable branch

- .circleci/config.yml
- longTest/LoadWith1pctDrop_test.go
- simTest/DemoteBootstrapLeader_test.go
- test.sh
- testHelper/simulation.go
- wsapi/debugapi.go
Tweak SimSetup to allow Fnode0 to be demoted and replaced as a Follower
This also swaps the identity - net gain is to allow a test where fnode0 isn't special
> Fd 1089 extend setupsim

- state/dbStateManager.go
- state/loadDatabase.go
- state/saveAndRestore.go
- state/stateConsensus.go
Applied changes to correct bal hash error when loading.
Also prevent double loading of genesis in edge case of loading from a database
with only the gensis
> FD 1124 BalanceHash Error rebase to Xuan

- state/state.go
pull request for https://github.com/FactomProject/factomd/issues/740
> fix loading of custom cert paths

- support/dev/factom/factomd_1.conf
- support/dev/factom/factomd_2.conf
- support/dev/factom/factomd_3.conf
Pull request for https://github.com/FactomProject/factomd/issues/677
> FD-924 Docker dev environment misconfigured

- .circleci/config.yml
> Fd 898 use golang 1 12 on ci

- common/primitives/buffer_test.go
- common/primitives/conversions.go
- common/primitives/conversions_test.go
- common/primitives/error.go
- common/primitives/error_test.go
- common/primitives/hash_test.go
- common/primitives/json.go
- common/primitives/json_test.go
- common/primitives/key.go
- common/primitives/key_test.go
- common/primitives/log.go
- common/primitives/merkle.go
- common/primitives/merkle_test.go
- common/primitives/signature.go
- common/primitives/signature_test.go
- common/primitives/timestamp.go
- common/primitives/timestamp_test.go
- common/primitives/util.go
- common/primitives/util_test.go
- common/primitives/varint_test.go
This check in is all comments being added, or receiver name changes for consistency.
> Purely Adding Comments or receiver name changes

- common/primitives/binary.go
- common/primitives/binary_test.go
- common/primitives/buffer.go
- common/primitives/buffer_test.go
- common/primitives/hash.go
- common/primitives/key_test.go
- common/primitives/merkle_test.go
- common/primitives/random/random.go
- common/primitives/random/random_test.go
- common/primitives/signature_test.go
- common/primitives/util_test.go
- common/primitives/varint.go
Code modifications amidst comments.
> Xuan factable changes try 3

- wsapi/wsapiV2_test.go
tweak test for new expected behavior
> update assertions after we fixed doule-process-coinbase bug

- state/dbStateManager.go
- state/loadDatabase.go
- state/saveAndRestore.go
- state/stateConsensus.go
Also prevent double loading of genesis in edge case of loading from a database
with only the gensis
> Applied changes to correct bal hash error when loading.

- LICENSE
this was added in pull requests https://github.com/FactomProject/factomd/pull/824 and https://github.com/FactomProject/factomd/pull/801
> Update license to reflect new library used in FD-450

- state/factoidstate.go
This restores code that existed in parchment
CoinbaseCancel Test passes for me locally now
> restore behaivor from parchment

- common/constants/ack.go
- common/constants/constants.go
- common/constants/runstate/runStates.go
- common/constants/servertype/serverTypes.go
- common/entryBlock/eblock.go
- common/entryBlock/eblockBody.go
- common/entryBlock/eblockHeader.go
- common/entryBlock/eblockHeader_test.go
- common/entryBlock/eblock_test.go
- common/entryBlock/entry.go
- common/entryBlock/entry_test.go
- common/entryBlock/specialEntries/ferEntry.go
- common/entryBlock/specialEntries/ferEntry_test.go
- common/entryBlock/specialEntries/identityEntry.go
- common/entryCreditBlock/commitChain_test.go
- common/entryCreditBlock/commitEntry_test.go
- common/entryCreditBlock/commit_test.go
- common/entryCreditBlock/commitchain.go
- common/entryCreditBlock/commitentry.go
- common/entryCreditBlock/ecblock.go
- common/entryCreditBlock/ecblockBody.go
- common/entryCreditBlock/ecblockHeader.go
- common/entryCreditBlock/ecblockHeader_test.go
- common/entryCreditBlock/ecblock_test.go
- common/entryCreditBlock/increasebalance.go
- common/entryCreditBlock/increasebalance_test.go
- common/entryCreditBlock/minutenumber.go
- common/entryCreditBlock/minutenumber_test.go
- common/entryCreditBlock/serverindexnumber.go
- common/entryCreditBlock/serverindexnumber_test.go
5 Separate commits.  One commit of 24 files is ALL comments and receiver name changes. The other commits have minor refactors that you need to look more closely at.
> Fd 1211 factable branch

- wsapi/ack.go
Change got left behind in rollup2
> Added of date for data commit entry to endpoint "ack"

- wsapi/debugapi.go
- wsapi/wsapi.go
- wsapi/wsapiV1.go
- wsapi/wsapiV1_test.go
- wsapi/wsapiV2.go
conform to standard RPC  behavior
> Fd 1224 set 200 status on rpc errors

- engine/p2pProxy.go
- p2p/connectionManager.go
- p2p/connectionManager_test.go
- p2p/controller.go
- p2p/parcel.go
- p2p/peer.go
- peerTest/BrainSwapA_test.go
- peerTest/BrainSwapB_test.go
- peerTest/NetSyncA_test.go
- peerTest/NetSyncB_test.go
- peerTest/README.md
> Fd 677 xuan gossip revert

- state/state.go
closes: #784 
A small fix to just not calculate the fees for the coinbase transaction.
> Don't display fees for the pending coinbase transaction

- registry/registry.go
- registry/registry_test.go
- worker/thread.go
Add OnReady phase to thread initialization process
> add onReady thread init phase

- CLA
> Update CLA -  TRGG3R (Nolan Bauer)

- state/grants.go
Updated to include grant payouts for Factom Protocol grant round 19-04
> grants.go Grant round 19-04 inputs

- wsapi/server.go
- wsapi/wsapi.go
cherrypick change for confetti release
> Fd 1223 correct port fwd api behavior 

- p2p/configuration.go
- p2p/controller_cat.go
* prevent the seed-server feedback loop by increased redial interval
* randomize selection of outgoing peers to distribute upload speeds
> Minor fixes for beta0

- common/messages/electionMsgs/authoritylistInternal.go
- common/messages/electionMsgs/electionAdapter.go
- common/messages/electionMsgs/electionAdapter_test.go
- common/messages/electionMsgs/electionMsgTesting/controller.go
- elections/elections.go
- engine/NetStart.go
- modules/event/event.go
- modules/query/query.go
- state/pubsub.go
- state/state.go
- state/stateConsensus.go
- wsapi/wsapiV2.go
Added elections.New constructor
Adjust Elections to use new Query API
add a new publisher to broadcast when Authority set changes ( for later use by other modules)
added OnExit behavior to stop processing messages
> Fd 1268 election pubsub integration2

- modules/livefeed/README.md
- state/stateConsensus.go
This is a minor PR that has no changes other than making some grammatical adjustments.
Motivation: I've been using the live feed to monitor the node and the typo in the database message bothered me, so I fixed it and made some adjustments to the README.
> [Wax] Minor grammar updates to live feed api

- p2p/controller_connections.go
PR that addresses https://github.com/FactomProject/factomd/issues/1020
Only displays the error if the shutdown wasn't initiated properly, display a debug notice otherwise.
> [Wax] Only display error for irregular shutdown

- common/constants/constants.go
- state/saveAndRestore.go
- state/saveAndRestore_test.go
* Bump version to 14
* Remove fields deprecated in Wax due to entrysync rework
* Remove some comments
> FastBoot version 14

- wsapi/wsapi_test.go
Re-implements #990 on top of wax to fix a race condition in unit tests
> Fix flaky https test

- wsapi/server.go
Use the right variable when recovering.
> Build bug redux

- wsapi/server.go
- wsapi/wsapi_test.go
> [Nowax] Fix flaky https test

- engine/factomParams.go
- simTest/factomd_test.go
- test.sh
> [Nowax] Remove compiler version check

- simTest/factomd_test.go
> [Nowax] Fix DBsigEOMElection unit test

- common/messages/electionMsgs/fedVoteLevelMsg.go
- state/stateConsensus.go
> [Nowax] Always set LeaderChainID

- wsapi/server.go
Rebase of #951 and a cherry pick from #1068
> [Nowax] Handle API panics more gracefully

- common/factoid/fblock.go
- common/interfaces/block.go
- common/interfaces/state.go
- common/interfaces/transaction.go
- engine/simControl.go
- state/state.go
- state/stateConsensus.go
> [Nowax] Stop invalid coinbase in pending transactions

- wsapi/wsapi_test.go
Cherry pick https://github.com/FactomProject/factomd/pull/1052
> Fix flaky TestAuthenticatedUnauthorizedRequest (#1052)

- wsapi/wsapiStructs.go
- wsapi/wsapiV2.go
- wsapi/wsapiV2_test.go
> [Nowax] Make raw data optional in API Requests

- state/rateCalculator.go
The Ratecalculator was technically thread safe, as in it didn't crash when accessed by multiple threads, but it wasn't "thread consistent", since it was theoretically possible to update the values while in the middle of loop, making the latter yield inconsistent results.
This change makes the rate calculator use a mutex instead of atomically swapping uints independently so that a single loop execution is always consistent.
> [Nowax] Make RateCalculator thread consistent

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
code of conduct is the standard (unmodified) Covenant Code of Conduct that is used in many open source projects.
Contributing.md is a basic version to get started.
> Add contributing and code of conduct

- .dockerignore
- README.md
- events/eventservices/eventSim_test.go
- test.sh
cherry-pick https://github.com/FactomProject/factomd/commit/b888bfaac9e12099f9e2045c45b27d2222908360
> remove references to glide (#1046)

- Utilities/CorrectChainHeads/correctChainHeads/correctchainheads.go
- modules/chainheadfix/fix.go
- modules/chainheadfix/head.go
- state/state.go
> [Nowax] Multithreaded Chainheadfix

- README.md
- docs/simulator.md
Rewrote a brand new README, with the most critical information in it.
Moved the simulation documentation to a separate file (I haven't reviewed/modified it).
> doc: new README

- .gitignore
- Utilities/snapshot/pkg/balances/balances.go
- Utilities/snapshot/pkg/balances/load.go
- Utilities/snapshot/pkg/load/chain.go
> Remove pkg from ignore file
