common/interfaces/state.go
common/messages/dbstate.go
common/messages/dbstate_test.go
engine/printSummary.go
engine/simControl.go
state/dbStateManager.go
state/processList.go
state/state.go
state/stateConsensus.go
state/stateDisplay.go
state/state_test.go
testHelper/testHelper_test.go
wsapi/wsapiV2.go

This is actually just a small update.  Rolled into this is also a fix to GetHighestSavedBlk() and GetHighestCompletedBlk() which were reversed in actual function.  This change is just a rename of one for the other in the code.

Sof 415  Fix to only ignore messages once at boot, even if the network delays.  

---

engine/simControl.go
state/dbStateManager.go
state/processList.go
state/processListManager.go
state/state.go
state/stateConsensus.go

Avoids issues with backing out the database when blocks are not shared among the leaders.

Sof 399:  Wait to the EOM before we save to disk

---

state/state_test.go

Not sure why the code expected 10 blocks.  If we wait long enough to have 10 blocks, the unit tests will take forever.  Also the genesis block has changed, so the hash had to be updated.

Fixed test

---

wsapi/wsapi.go

a change to the v2 api call that enabled corrected identity utilization
changes an entry request to a message request.  updated api v1 skin to
messageRequest

updated v1 commit entry api

---

util/config.go

Setting parameters that don't map to real values in our struct will no longer cause factomd to completely ignore the config file and revert to the defaults.

Panic on errors in config file (Rather than silently load defaults)

---

state/dbStateManager.go

I keep putting this in, and it keeps getting lost in the shuffle. 
Ignore the nil process list, return, and process later when the ducks are actually in order.

check for nil

---

common/messages/dbstate.go

calls the value already helded instead of recomputing it every time.

switched getHash call in messages to call messagehash

---

p2p/connection.go
p2p/controller.go
p2p/parcel.go
p2p/parts_assembler.go

* Moves partial parcel assembly from connection to the controller (also separated the code to a separate file)
* Allows parts to arrive in random order, the final full message is assembled according to the AppHash from the original message
* If the expected parts stop arriving, cleans the existing entries after min 10 minutes (the check is performed every time a part arrives)
* Deacreases payload size from 10kB to 1kB to avoid gob errors

SOF-514: parts mixup fix

---

state/ack.go

while syncing, there may be nil process lists

watch for nils in processlist on factomtransaction search

---

.coverignore
.travis.yml

* Ignores vendor dir when unit tests are run
* Integrates coveralls to ensure unit test coverage
* Adds a `.coverignore` file that lets you specify which files should be excluded from coverage calculations, the lines in this file can contain any wildcards supported by https://golang.org/pkg/path/filepath/#Match

Fix build, add coveralls support

---

state/validation.go

At 20 ms, we are burning too much CPU when idle for some tests.
No significant effect on response times and performance in my testing 
This value dictates how long we sleep when we provably have nothing to do.  Means we MIGHT waste 180 ms more time before we start processing a message, but will not delay processing a group of messages (i.e. heavy load will not be impacted).

change sleep on idle from 20 ms to 200 ms

---

controlPanel/searchDB.go

Fixed control panel showing invalid addresses as valid
Simple search 'FA3eQZMJBVpsTKRB19x9tC1wD3fzwSi4Q7Y5BW32rYw6P5yyWqfrExtracharacters' to see if it has been fixed. Also made it break out of the switch and go through the other searches if the address search fails. This is because EC and FA are valid hex, so there could be a case where an entry with "FA..." or "EC..." get's improperly rejected. Now it is fixed.

Sof 606 into develop

---

wsapi/debugapi.go

Summar --> Use short string. Cleared it with Veena
ProcessList --> Use string method on interface. The interface itself cannot json marshal for some reason, but the struct is way overkill for this return. Cleared with Veena
ReloadConfig --> Not useful IMO, but fixed. If passing a filename with length 0, it uses defaults. Pass default config name, and pass the network type, as changing this could panic factomd. So you don't want to change network types by this

Adjustments to some of the debug calls

---

state/stateConsensus.go

You will note that we execute the message on line 171.  Then (if the message is in process) again on about line 196.  That can make us process a dbstate message twice.

remove double processing of messages

---

state/entrySyncing.go

We took this assignment out, but we actually need it.

set the EntryDBComplete flag to HighestSaved if all is synced

---

database/leveldb/leveldb.go

There was no locking around LevelDB.Put(), and PutInBatch(). 
BoltDB has the locking

Added a lock around LevelDB Put()

---

common/interfaces/state.go
state/instrumentation.go
state/state.go
state/state_test.go
wsapi/wsapiStructs.go
wsapi/wsapiV2.go

Moved the calculation for transaction rate to a loop that is guarenteed
execution, and made it execute every ~3 seconds. This is a decent estimate
of transactions seen by the node

Added an API call to get transaction rate

---

p2p/controller.go
p2p/instrumentation.go

Right now, a node with many connections does not participate with broadcasting beyond 4 nodes, effectively dropping out of the network.

FD-52: Broadcast to 1/4 of connections

---

state/dbStateManager.go
state/loadDatabase.go
state/state.go
state/stateConsensus.go

Needed to protect the database.  A bit of a corner case that might not really be possible often in the real world except when we reboot the network.

FD-69:  More debugging, fix OBO error in database loading

---

common/messages/dbstateMissing.go
engine/simControl.go
state/stateConsensus.go

Check the len of the InMsgQueue and don't respond with data when behind.

FD-78:  Limit dbstate requests and missing message requests when behind

---

p2p/connection.go
p2p/protocol_test.go

The deadline is a race condition, stopping a read with partial data,
that error causes the connection to go offline. Receiving lots of
data will trigger this often.

Fd 41 - Fixing Connection thrashing

---

engine/instrumentation.go
state/instrumentation.go
state/queues_test.go

float64(time.Since().Nanoseconds) does not guarentee positive results
To combat this, use gauges instead of counters in prometheus to avoid panics

Time durations can be negative

---

state/processListManager.go
state/processListManager_test.go

Avoids recursively looping over the list of process lists when it is not necessary.

Refactor creating process lists on Get

---

p2p/connection.go

Same as #451 but against the `communitynet-m3` branch
Fixes two separate issues:
* When the connection was going offline due to some error, it was
possible in some cases for the goOnline function to reinitialize gob
encoder/decoder without restarting the TCP/IP connection. The new
decoder would start reading data from the old connection, but due to
buffered reads the old decoder might have left the data in the
connection in the middle on the message. This caused an error which
again caused the connection to go offline and online and repeat the
problem, so as a result the whole connection was stuck in an infinite
error loop. This change ensures that the connection is closed when going
offline.
* The gob.Decoder.Decode function returns io.EOF when there is nothing
to read. This wasn't …

Fix errors after gob enc/dec were reinintialized (communitynet-m3)

---

.circleci/config.yml
Dockerfile
Dockerfile.alpine

circleCI was failing with golang 1.10.2 due to a not-found error.  Try 1.10.3.
fixes this error in circleCI
```
Build-agent version 0.0.6347-92eac3d (2018-06-13T18:13:12+0000)
Starting container circleci/golang:1.10.2
image cache not found on this host, downloading circleci/golang:1.10.2
Error response from daemon: manifest for circleci/golang:1.10.2 not found
```
https://circleci.com/gh/FactomProject/factomd/4751

update to golang 1.10.3

---

state/dbStateManager.go

Prevent empty coin bases from be create if there are no grants for the block.

Fd 583 no empty grant coin bases

---

engine/loadcreate.go

Pervious version failed to buy enough ECs, and eventually we filled the queues with commits and reveals that were not backed by the right number of ECs.
Only for testing.

FD-608 Change SimCtrl wallet to simulate the small EC buys when generating load.

---

state/processList.go
state/saveAndRestore.go

Setting DBHeight Base fixed the memory spike issue.
Found that when we no longer load a process list for all blocks, this caused the db height in the Header to be incorrect so added code to correct this when it happens.
TODO: still need to work on adding a unit test for this

fix issue /w memory on fast boot

---

common/entryBlock/entry.go

Add named return values to the function so that the deferred function can properly modify the returned error. 
Naming the return values made it clear that the returned byte slice from this unmarshaler is never not nil. This should be refactored to only return the error.

Fix Issue #624

---

common/messages/ack.go
state/authority.go

I believe this prevents the problems described in FD-850, which turned out to be two-fold.
1) The acceptance of Acks's DBHeight has been moved underneath the check that filters out Acks in the distant future. The highest distance now accepted is capped at LeaderHeight + 5.  
2) The signature validation adds a sanity check to filter out messages that do not have a signature at all

improving handling of malformed messages

---

common/messages/electionMsgs/syncMsg.go

Small fix to drop any outside SyncMsgs, they are internal messages only.
(TimeoutInternal can't be unmarshaled and is already protected from being accepted via network)

FD-886 Prevent syncmsgs arriving from the network

---

engine/factomParams.go
p2p/connection.go
p2p/protocol.go

> There is a bug in the p2p code that handles disconnectiong peers poorly.  If I understand correctly the problem, the tcp connection gets dropped by the other node, but the p2p code doesn't recognize it.  we need to have a way to close a connection when the tcp connection drops.
The current way it works:
Command line argument "deadline" is [defaulted at 1000ms](https://github.com/FactomProject/factomd/blob/d2e5799ab97ce87030bd15ae210080a2e54ae5eb/engine/factomParams.go#L61) and the text is incorrect (see next points).
There's a [write deadline](https://github.com/FactomProject/factomd/blob/d2e5799ab97ce87030bd15ae210080a2e54ae5eb/p2p/connection.go#L468) timed at 500 * command line param (8 minutes, 20 seconds).
All [EOFs are ignored](https://github.com/FactomProject/factomd/blob/d2e5799ab …

Fd 858 close tcp connection

---

wsapi/wsapi.go

This arises from a discussion with Anton, Jay, Matt, and I about a status endpoint. This arises from discussion about #671 in which the solution is to create a standalone, separate program to determine readiness from facts about the server. This PR is to propose adding a `GET /status` endpoint to the node with a variety of information the user can find for determining readiness. This helps satisfy some elements that the open api project and other projects want to use, in particular:
1. A `GET` route to return 200. For now this is good enough singular point for checking liveness.
2. Returns a collection of information to give insight to the user about readiness.
This is based on a sketch so let me know if this needs to go to a different branch or get rebased or moved to a different path, …

Fd 869 add status check to api

---

state/entrySyncing.go

This is my first commit so I'm writing down all the details.
During my debug session I noticed that EntryDBHeightComplete is set to s.EntryDBHeightComplete = scan - 1. The first time after one or more new blocks were saved to the DB this makes sense because GoSyncEntries still has some work to do. But at the end of the function s.EntryDBHeightComplete is set to the highest block.
The next iteration of the loop will set it back to scan-1 and after the sync code completes back again to the highest block. When running a custom net with a small database the code in between executes so fast that this behavior is difficult to observe, but with a production database the EntryDBHeightComplete will be at -1 for quite some time.
Please see the comments in the code review on the "files changed" …

FD-922: Fixed 2nd pass flagging (EntryDBHeightComplete)

---

common/globals/globals.go
engine/NetStart.go
engine/factomParams.go
factomd.conf
p2p/protocol.go
state/state.go
util/config.go
util/config_test.go

This change raises the cap of max incoming connections to accommodate intermediate network growth, as well as providing config and command line parameters to change these numbers for future adjustments or customization for seed nodes.
Changes:
* Global variable `p2p.MaxNumberIncomingConnections` raised from 150 to 200
* Configuration file variables: `App.P2POutgoing` and `App.P2PIncoming`
* Command line flags: `-p2pOutgoing` and `-p2pIncoming`
Order of evaluation is (from lowest to highest): p2p package default variables, config file, command line

Configurable p2p incoming and outgoing flags

---

common/messages/electionMsgs/syncMsg.go
common/messages/electionMsgs/syncMsg_test.go
common/messages/electionMsgs/timeoutInternal.go

Continuation of https://github.com/FactomProject/factomd/pull/669 
I only removed Unmarshalling support in SyncMsg because MarshalBinary is still used in GetMsgHash(), which in turn is used by LogMessage/MessageTrace. This doesn't pose a security risk on its own because messages can't arrive via network anymore and if the code were to be removed, an attacking node could always re-implemented Marshalling on their end anyway. 
TimeoutInternal already behaved this way, I just cleaned up some of the formatting.

Election Sync Cleanup

---

controlPanel/controlPanel.go
engine/profiler.go

Continuing from: https://github.com/FactomProject/factomd/issues/675
I have also added the separate mux for prometheus. The API already has a separate one, since it's using the [factomproject/web](https://github.com/FactomProject/web) server. 
HTTPs still works for both the control panel and the api, and pprof/prometheus are not accessible via port 8090 anymore, likewise for pprof and prometheus being able to access each other or the control panel. The API has always been separate and was not susceptible to this in the first place.

FD-925_use_different_web_service_muxes

---

engine/MsgLogging.go

The command line flag -runtimeLog lets you enable/disable the runtimelog, which is the log of messages you can print via the console "m" command. It buffers 4 seconds worth of messages internally, after which the buffer is cleared.
At the moment, the function that buffers message doesn't respect the setting whether or not it's enabled. This fix will:
* Disable message buffering when the runtimeLog flag is turned off, saving a little bit of memory and cpu
* Print out an info message if someone turns on message logging in the console with the setting disabled

Runtimelog doesn't respect its own enabled setting

---

common/constants/ack.go
common/messages/ack.go
state/dbStateCatchup.go
state/dbStateCatchup_test.go

Caused by an off by one when choosing what dbstates to request.

FD-1084 : A synced node keeps requesting dbstates even after it is synced

---

simTest/BrainSwap_test.go
state/dbStateManager.go
state/state.go
state/stateConsensus.go
wsapi/wsapiV2.go

Write entries when they are processed.  In addition, put them into the old maps so that pending entries don't get broken.  But we do remove the block oriented writes of entries between blocks.

FD-795 Optimistic Entry Writing

---

.circleci/config.yml

This isn't needed, I don't think we rely on it for anything 
I've added a slack integration to replace this.

remove zapier webhook

---

common/constants/constants.go

This is the same version that gets generated with Parchment.  The new version of factomd (xuan) will need to have the version set to 13, because the Cotton version does not have the fix for stopping at blocks divisible by 1000 (FD-1091).

bump savestate version so that it gets rebuilt with the balancehash fix

---

engine/factomd.go
state/dbStateManager.go
state/loadDatabase.go
state/saveAndRestore.go
state/state.go
state/stateConsensus.go

This branch also includes fixes from FD-1124, which are already in cotton.

FD-1169 Allow DBsigs that are created before boot time to be valid

---

common/constants/constants.go

The federated servers are running v6.4.1, which has the bugfix for double counting of transactions in some of the blocks, FD-1124.
6.4.1 does not included the bugfix for FD-1091, which affects nodes that are shut down on blocks divisible by 1000, but that is included in the parchment/xuan code.  In order to fix any problems that may have been introduced by that bug, force a rescan when installing xuan, so that the state is known to not have been built with either of the bugs.

FD-1171 bump savestate for xuan to 13

---

common/messages/ack.go
common/messages/directoryBlockSignature.go
common/messages/eom.go
common/messages/msgbase/MessageBase.go
engine/NetworkProcessorNet.go
state/factoidstate.go
state/stateConsensus.go

This adds a 20 minute grace period for DBsigs, that the other server messages have which was introduced in 6.4.1 for an emergency patch.  
This pull also fixes a pokemon bug and fixes printing of some timestamps

FD-1208 20 minute grace for DBsigs + pokemon + timestamps

---

wsapi/server.go
wsapi/wsapi.go

TL;DR make the http request always able to get the right Server instance instead of relying on user input
This was a problem that occurred for @ilzheev's open node when updating from 6.4.1 to 6.4.3. The API returned a 400 error when requests were routed through a proxy, but were fine when accessing the endpoint directly. 
The issue is that 6.4.3 introduces a change of how the "Server" is retrieved. In [wsapi/wsapi.go](https://github.com/FactomProject/factomd/blob/bb94084344fd919185d065bef2662d69087ea293/wsapi/wsapi.go), the start/stop/set functions store the "Server" by the associated State's port, which is used in unit testing to create several different test instances on different ports. In a normal node, the Server gets stored in "8090".
Before 6.4.3, the Server was stored in the …

Make API pick the right server instance

---

wsapi/server.go
wsapi/wsapi.go

Restores the old API behavior where port specified in host header does not not affect routing

Fd 1223 correct port fwd api behavior

---

wsapi/debugapi.go
wsapi/wsapi.go
wsapi/wsapiV1.go
wsapi/wsapiV1_test.go
wsapi/wsapiV2.go

closes: https://github.com/FactomProject/factomd/issues/893
This is an inconsistency of the jsonrpc spec. the tl;dr is that all responses with valid jsonrpc formatting should receive a status code of 200, including jsonrpc errors. At the moment, the factom client does not actually check the status code of responses at all.
This may have unintended side effects if there are libraries out there that wrongly depend on the http status code to detect if a json response is an error or not. 
This PR replaces all Status code 400 responses with status code 200 and updates the V1 unit test to check for an RPC error instead of the status code.

Return status code 200 for JSONRPC errors in the factomd api

---

state/processList.go
state/processList_test.go

Laurens also added an extra unit test which fails when the fix is removed.

Fd 883 failing back to back brainswap longtest

---

registry/registry.go
registry/registry_test.go

Adjust thread groups to assume OnExit will cause the running goroutine to exit
Ensure OnComplete is run for all threads
also adjusted to use only 2 goroutines per 'thread' - one for running and one for exit

adjust thread waitgroups

---

state/grants.go

Add coinbase for Bug bounty payouts according to core committee tracking sheet:
https://docs.google.com/spreadsheets/d/15fo9PCNt4meJGSd-V9iZENAiPTUx7dLpd990tH1dADY/edit#gid=0
(only available to core commitee members)

Bug bounty payouts 2019-Q4

---

common/interfaces/msg.go
common/messages/msgbase/MessageBase.go
engine/NetworkProcessorNet.go
state/instrumentation.go
state/stateConsensus.go

This allows better analysis of the timing delay
of follower to the various leaders on the network.
This allows some basic latency tests to be done
on a follower following the blockchain.
(Only done for Eoms)

Add msg/ack delay prometheus metrics

---

wsapi/wsapiV2.go

closes: #947 
The elections.Elections struct isn't thread safe, which has caused multiple node crashes for the API "diagnostics" call. It first retrieves the index of the server being elected, then several lines later tries to retrieve the "rounds" count for that server. The "rounds" slice is reset whenever an election is finished and then zero-padded on demand. There are likely two edge cases that can cause a crash:
1. An election finishes right after the index is retrieved, truncating "rounds" to a zero-length slice
2. A new election is started but the "rounds" array hasn't been zero-padded yet
The proper fix would be to create a snapshot of the current "Elections" state via a deep copy to use for the diagnostics call, or provide thread-safe accessor functions for the relevant data, one …

Hotfix for diagnostics index out of range error

---

longTest/LeaderModule_test.go
modules/leader/thread.go
pubsub/examples/unsubscribe/main.go
pubsub/pBase.go
pubsub/pThreaded.go
pubsub/pThreaded_test.go
pubsub/swMsgFilter_test.go

Added methods for interacting with threaded publisher 
to avoid data race in testing
Did not update the Interfaces - unsure if we want to use this style of interaction during the 'standard' usage of the pubsub package.

Fd 1225 sync pubthreaded calls

---

wsapi/debugapi.go
wsapi/wsapi.go
wsapi/wsapiV1.go
wsapi/wsapiV2.go

This is a compatibility issue that came to light in testing 6.5.1. PR #897 changed the API to return status code 200 for json-rpc errors, but the factom.js client relies on status codes to determine whether or not a request is an error. Functionality is being changed back to preserve backward compatibility.
Reversing this means the FAT/factom client is no longer fully compatible due to https://github.com/AdamSLevy/jsonrpc2/issues/3. However, this is a fairly benign issue that results in FAT/factom to return a json-parsing error rather than an appropriate error.

Reversing API status code

---

Utilities/NetworkTester/NetworkTest.go
controlPanel/connectionManagement_test.go
controlPanel/controlPanel_test.go
events/eventEmitter_test.go
events/events_test.go
events/eventservices/eventSender_test.go
p2p/controller_connections_test.go
p2p/util_test.go

Looks like there were a couple of unit tests not passing:
* the control panel tests were using the old p2p metrics struct
* the live event api relied on a p2p global variable to set their channel size for some reason
* Test_controller_listen ran into a goroutine race condition that failed on circle but not my dev machine
* Testing IP lookup failed due to differences in ipv4 and ipv6 (that test is disabled now since we can't guarantee which one is used)

[p2p2 6.6.0 beta] Fix control panel unit tests

---

modules/worker/signal.go

The interrupt handler left out the most important thing: exiting the app. It just kept running and capturing Ctrl+c signals, thereby softlocking the app and requiring killing the process to exit. It also had a superfluous "isShutdown" flag that didn't make a lot of sense if the program exits. This was also problematic because importing some parts of the factomd into other projects would hijack Ctrl+c.
Changes:
* Use sync.Once to start the interrupt handler on demand
* Use defers instead of holding functions in a slice
* Call os.Exit(0)

[Wax] Interrupt Handler fix

---

modules/registry/registry.go
modules/worker/thread.go

The worker.init() function determines the `Prefix` from the filepath and tries to apply that to all "caller" strings. This makes the worker package unusable outside of the factomd project, since the runtime.Caller file may yield a string that's shorter than `Prefix`. The cost of the additional check should be negligible.
Changes:
* Turn getting the Caller string into an exported function
* Only shorten the string for calls inside factomd
* Add fallback if no caller can be established

[Wax] Make worker.Prefix use safe for outside libraries

---

common/entryBlock/entry.go
common/entryCreditBlock/increasebalance.go
common/entryCreditBlock/minutenumber.go
common/entryCreditBlock/serverindexnumber.go
common/messages/electionMsgs/timeoutInternal.go

This PR is identical to #967, only it's based on Wax instead of master.
Changes five functions that will always return nil from triggering the error that checks for nil results.

[Wax] Don't check for nil when nil is expected

---

.circleci/config.yml

Right now all PRs fail circle because of docker_build, which is restricted to a few branches. This PR limits the docker_build workflow to only those branches.

[Wax] Only run circle docker_build for a few branches

---

p2p/controller_routing_test.go

Mirror of https://github.com/WhoSoup/factom-p2p/pull/48
> In the Test_controller_manageData, one of the tests was routing a peer share, which happens inside a goroutine. A race condition sometimes occurred where the controller was stopped and the unit test checked before the goroutine finished.

[Wax] Fix flaky unit test

---

Utilities/CorrectChainHeads/correctChainHeads/correctchainheads.go
modules/chainheadfix/fix.go
modules/chainheadfix/head.go
state/factory.go

Motivation: I'm compiling and starting factomd a lot these days and every time I load the MainNet database, there's a ~20 second period where the chain head fix utility runs. I looked at the code and found it to be pretty incomprehensible and also single-threaded. I wanted to see if I could speed up the performance by multithreading the algorithm.
The original algorithm took between 20-21 seconds to run on average. The new code takes 11-12 seconds. The limiting factor now seems to be database i/o.
Description of new algorithm taken from comment:
https://github.com/FactomProject/factomd/blob/bbc5c85fcf05f03f72a4eb76493176c395418ff4/modules/chainheadfix/fix.go#L18-L28
Note: the old algorithm also contained a check for eblock parent block consistency checks. Is this still needed? I was …

[Wax] Multithreaded ChainHeadFix

---

wsapi/wsapiStructs.go
wsapi/wsapiV2.go
wsapi/wsapiV2_test.go

I was analyzing D/EC blocks for an unrelated issue and noticed that the API will always send both the json data and the raw message, even if you don't need both.  This wastes quite a bit of bandwidth particularly for EC blocks (they're huge due to PegNet). There already is a "get-raw" endpoint for those that only need the raw data but no way to get just the json without the raw.
This changes the following endpoints:
* admin-block
* factoid-block
* entrycredit-block
* dblock-by-height
* ecblock-by-height
* fblock-by-height
* ablock-by-height
("directory-block" itself doesn't even have a raw option, oddly enough)
It adds an optional "noraw" argument to the json call that accepts either "true" or "false". If "noraw" is not present, everything works as before. If "noraw" is true, the API …

Make raw data optional in API Requests

---

p2p/seed.go
p2p/seed_test.go

With the change to localseed.txt to remove debug IPs, the node reported an error `time="2020-08-20T10:27:58+02:00" level=error msg="Badly formatted line []" package=p2p subpackage=Seed url="https://raw.githubusercontent.com/FactomProject/factomproject.github.io/master/seed/localseed.txt"`. 
Changes:
* Skip blank lines during peer file parsing without errors

[Wax/P2P2] Allow empty seed files

---

engine/NetworkProcessorNet.go
modules/pubsub/registry.go

This was driving me crazy because nobody else mentioned that the code crashed on startup. Turns out it wasn't crashing for anyone else (thanks @PaulBernier) and it's a platform specific issue due to pubsub using filepath.Join, which is meant for platform specific file paths, and one instance of a hardcoded path.
Changes:
- Use platform independent method in pubsub.GetPath
- Standardize path usage for Node/msgs channel
Note: this may have a merge conflict with https://github.com/FactomProject/factomd/pull/1005, which also changes the name. The change in #1005 supersedes this line.

[Wax] Platform independent paths

---

common/factoid/fblock.go
common/interfaces/block.go
common/interfaces/state.go
common/interfaces/transaction.go
simulation/simControl.go
state/state.go
state/stateConsensus.go

This PR is a fix for #1006. This works by adding a flag to FBlocks that track whether or not the coinbase tx has been patched, and in return GetPendingTransactions only returns the coinbase if it has been patched. There are better ways to fix this, such as not creating the coinbase at all until the real timestamp is in, but the code frequently relies on the coinbase transaction existing. I figured this was the least-invasive method that doesn't affect existing behavior.
Changes:
* Add coinbasePatched flag to FBlock and support methods in both the block and the interface
* Add DBHeight to PendingTransaction result that indicates the expected height of the transaction (or 0 for transactions in holding)
* Change the consensus code to use the new FBlock functions instead of blind casts
* …

[Wax] Stop invalid Coinbase transactions from showing up in pending-transactions

---

engine/NetStart.go
state/stateConsensus.go

Some of the code in state relied on channels existing but due to race conditions not having been created yet. They were checked for being nil. This PR initializes the channels before starting the node.
Fixes #1039

[Wax] Build registry before running state

---

engine/factomParams.go
simTest/factomd_test.go
test.sh

I upgraded my local setup to go 1.15. As a side effect it looks like it has better static analysis and complained about some string conversion, and for good reason, so I fixed that. Finally, do not disable `vet` for tests.

remove isCompilerVersionOK check

---

wsapi/wsapi_test.go

The issue that 2 cases were sharing the same io.Reader, so depending on the order of the tests the reader would be consumed or not, making the test sometimes pass, sometimes fail.

Fix flaky TestAuthenticatedUnauthorizedRequest

---

.circleci/config.yml
engine/NetworkProcessorNet.go
test.sh

This PR does 3 things:
1. Make the gofmt step actually work in CircleCI: until know that step would *always* work no matter what is pushed, because it was using option `-w` that just rewrites files locally...
2. But gofmt step in front of tests, we should fail because of linting as early as possible, no need to waste time testing if the job is going to fail anyway.
3. Fix one file that was not properly formatted (but because of 1. never got noticed)

Fix gofmt step for circleci

---

engine/NetStart.go
engine/factomd.go
state/factory.go
state/stateSaver.go
util/config.go

This just help on not getting overwhelm unnecessary with the start up log. We can still do much better, but that at least remove useless or redundant logs.

improve startup logs readability

---

engine/NetStart.go
simulation/simControl.go

Re-enables the code to switch the control panel to a different sim node when manually selected in the console. This is mostly just uncommenting existing code and a minor change to pass the build variable.

Switch control panel in sim control

---

p2p/protocolV11_test.go

4093 + 4 = 4097 which is greater than the capacity of the buf slice of 4096
Error occurred: https://app.circleci.com/pipelines/github/FactomProject/factomd/406/workflows/4bae057b-dd48-4d4e-9027-8e6d1fad8895/jobs/18460

fix(test): flaky TestProtocolV11_readWriteCheck

---

wsapi/server.go

The golang server is able to handle panics inside of an http request without crashing* but at the moment, panics in are not handled gracefully. It a) prints the stacktrace to stderr, b) sends no output to the client. 
This change adds a panic recovery middleware that addresses both of these.
* If recovering from a panic, write the error to the API log file via `wsLog` like other API errors
* Return an "Internal Error" to the client
\* unless the goroutine causes another goroutine to crash due to multithreading issues or the panic is not recoverable

Handle API panics more gracefully

---

common/messages/electionMsgs/fedVoteLevelMsg.go
state/stateConsensus.go

This bug happened consistently in the `TestDBSigElection` unit test, where it attempted to read from a message's LeaderChainID that was `nil`. It took me a long time to figure out where the message actually came from, and the source is the election code, pushing an audit server's volunteer message into the process list as a directory block signature message. 
This fix is two-fold:
* Change the election execute code to always set a message's LeaderChainID before adding it to the process list
* Change the reading of LeaderChainID in the ProcessDBSig method to use the function rather than the field directly (the function will never return `nil`)
Only the first item is necessary for this to be fixed, the second change is just for consistency. 
So what caused this? I'm still not entirely sure. …

TestDBSigElection nil pointer error

---

modules/debugsettings/settings.go
simTest/MessageFilteringInput_test.go
state/state.go

The cause of this one turns out to be fairly simple: the value being set via the API call never made it to the BMV where it filtered them, due to the state function not having the debugsettings module implemented
Changes:
* Update debugsettings when input/output filter are set in state
* Fix typo in function name
Sidenote: This unit test is not windows compatible due to its reliance on `SystemCall`.

Fix TestFilterAPIInput unit test

---

engine/factomd.go
log/log.go
simTest/factomd_test.go
state/stateConsensus.go

This test wasn't working because the functionality it was supposed to test just wasn't implemented. Not sure if this code got lost somewhere in rollup or went wrong somewhere else.
Wax rewrote the --debuglog parameter to include both a path and a regular expression, but the parameter was ignored and the function call hardcoded to "./." (aka log every file in the CWD). Logging was enabled if --debuglog was set but otherwise it had no effect.
Changes: 
* Initiate the GlobalLogger in a new function (formerly `init()`) which is called in `engine.Factomd`, where the parameter can be passed to it
* Use the node's name in the logger (formerly hardcoded as "fnodex")
* Rewrite the unit test to use the golang built in functions to create temporary directories instead of doing it manually

Fix TestDebugLocation unit test / debuglog parameter

---

simTest/factomd_test.go

This unit test only failed occasionally, making debugging this very difficult, since each run takes approximately 3 minutes. I'm not entirely sure if this fixes the problem or just pushes the frequency so low that I haven't encountered another error.
In any case, I believe this was caused by some sort of race condition inside factomd due to the loops running too fast. `runtime.Gosched()` just allows the scheduler to interrupt the loop but it doesn't put the goroutine to sleep or anything like that, meaning that all the loops here were just running at full speed.
That means there could be a potential problem in a real world scenario of this occurring, though it should be noted that the test doesn't entirely reproduce the real world environment. A node in the actual network dropping behaves …

Fix DBsigEOMElection

---

engine/NetStart.go

The issue was that the peers weren't connecting to each other, due to two command line parameters never making it into the P2P config: the local network port override and special peers. The code used the config file settings but did not use the command line parameters.
Both unit tests (BrainSwapA/B and NetSyncA/B) pass with this change.

Fix peer tests (BrainSwap, NetSync)

---

Utilities/DatabaseGenerator/blockgen/generator.go
Utilities/DatabaseIntegrityCheck/DatabaseIntegrityCheck_test.go
Utilities/NetworkTester/NetworkTest.go

The /Utilities folder should probably be moved out of the repo at some point. It's a collection of related but separate applications. They were somewhat kept up to date but a few of them had build errors. It's not really a problem since factomd doesn't import them and so it compiles fine but it's still annoying to see on the UI.
Fixes:
* blockgen is updated to start with the registry
* NetworkTest is updated to start with the registry
* A unit test in DatabaseIntegrityCheck was using a function that was [removed in 2019](https://github.com/FactomProject/factomd/commit/5b401da82cb0e0d3cfac0a796608e85c74058cd3). I removed the unit test

Fix /Utilities build errors

---

common/entryBlock/entry.go
common/entryCreditBlock/increasebalance.go
common/entryCreditBlock/minutenumber.go
common/entryCreditBlock/serverindexnumber.go
common/messages/electionMsgs/timeoutInternal.go

A copy-paste of functionality that stops the error whenever someone buys EC.

[Nowax] Don't check for nil when nil is hardcoded

---

controlPanel/connectionManagement_test.go
p2p/seed_test.go
state/rateCalculator_test.go
wsapi/wsapiV1_test.go
wsapi/wsapiV2_test.go

Trying to track down a couple of flaky unit tests:
* wsapi/TestGetRaw failed occasionally because the http body response was closed on a nil pointer. There's probably an underlying issue somewhere that causes the request to fail sometimes but the unit test accepts a nil body as ok otherwise. Also improved some of the output of both V1 and V2 GetRaw tests
* controlPanel/NewRandomP2PConnection was throwing a warning
* p2p/seed_retrieve: race condition between the http server starting and the test executing on slower cpus
* state/TestRateCalculator: this unit test is really weird and fails every now and then due to race conditions

[Nowax] Unit Test Fixes

---

Dockerfile
Dockerfile.alpine

Circle keeps failing the develop branch because glide is still in the docker file. Removed the glide commands in there.

[Nowax] Remove glide from docker files

---

engine/NetStart.go

This is similar to #1074, though in this case, the command line network port override occurs too late to have an effect on the p2p config. The setting has been moved up to an appropriate place, as well as the "node name" setting.

[Nowax] Fix peer test / network port override

---

testHelper/testHelper.go
wsapi/wsapiV1_test.go
wsapi/wsapiV2_test.go
wsapi/wsapi_test.go

Looked at the unit tests that were failing in wsapi and noticed that all the unit tests were using the same port for the server, which worked fine on one machine but failed on another. This PR does the following:
* Introduce a delayedStart() that waits for the web server to be active when starting for all unit tests
* Automatically detect an available port on the local system and use the random port for the web server instead of multiple unit tests using the same port
This PR might not be strictly necessary depending on the setup.

[Nowax] wsapi unit test server consistency

---

activations/activationHeight.go
activations/activationHeight_test.go
state/state.go

Noticed that the /activations code was pretty messy, wanted to clean it up a bit:
* Use sync.Once instead of a bool to calculate network name
* Don't export structs not used or needed outside of package
* Add unit test that double check all the defaults
I discovered a bug where for networks that don't have a custom entry and the default is "disabled", it would always enable them on the first block. Essentially it checked for it and printed out "never activating" but returned true anyway. This fixes that, which has no effect on either MainNet or TestNet. It might have an effect on some unit tests that use a custom network, or any custom network out there.
For that reason, I changed the default to 0 (always active) to keep behavior consistent with how it used to work before.

Activation Bug Fix + Cleanup

---

Utilities/DatabaseCheck/EntryBlockChecks.go
common/globals/globals.go
common/globals/params.go
engine/NetStart.go
engine/factomParams.go
engine/factomd.go
events/eventservices/eventServiceParameters_test.go
factomd.go
testHelper/simulation.go

Wanted to clean up the entry point file a little bit:
* Remove '.' import in factomd.go
* Remove '.' import in engine
* Remove the "listen to stdin" param from engine.Factomd() and related calls since it's passed along with params already
* Move the printout of the params into the same file as the definition of params
* Use `tabwriter` for alignment
* Move parameters to their own file in globals package
* Make global parameter struct a reference

Cleanup of /factomd.go + Params
